################################################################################################
########## <<< Doesn't work on this project cause binding with noee-sass build >>>> ################
##########                                                                  ####################

version: '3'
services:
  frontend_app:
    container_name: breengrow-frontend
    # Build from Dockerfile on root directory
    build: .
    
    ports:
      - 5000:5000
    volumes:
      - /var/www/breengrow-frontend:/usr/src/breenGrow-frontend
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 5000