@startuml order diagram class

class Hive 
{
  - string name
  - string siret_number
  - array products
  - string street_address
  - string city 
  - zip_code
  - float lattitude
  - float longitude
}

class consumer {
  - string name
}

class Order 
{
  - int orderNumber
  - uuid consumerId
  - string hiveSiret
  - DateTime receivedAt
  - string orderStatus
  - float amount
  - collection orderLines
}

class OrderLine 
{
  - int lineNumber/Id
  - int orderId
  - int productId
  - int quantity
  - float price
}

class Product
{
  - uuid
  - name
  - description
  - price
}



Order  *--  OrderLine : > owns
OrderLine *-- Product : > owns

@enduml